/*
 * sycall_mount.h.S -- PS3 Jailbreak payload : mount syscall
 *
 * Copyright (C) Danger Blarg
 *
 * This software is distributed under the terms of the GNU General Public
 * License ("GPL") version 3, as published by the Free Software Foundation.
 *
 */
#ifndef MOUNT_H
#define MOUNT_H

#include <psl1ght/lv2.h>

#define SC_FS_MYMOUNT 42
#define SC_FS_MOUNT 837
#define SC_FS_UMOUNT 838

// credit to PS3MrEnigma for device list and filesystem types

// "generic" devices
#define DEV_FLASH "CELL_FS_IOS:BUILTIN_FLASH" // generic dev_flash
#define DEV_USB "CELL_FS_IOS:USB_MASS_STORAGE" // generic dev_usb
#define DEV_HDD "CELL_FS_UTILITY:HDD" // generic dev_hdd

// known devices
#define DEV_FLASH1 "CELL_FS_IOS:BUILTIN_FLSH1" // dev_flash
#define DEV_FLASH2 "CELL_FS_IOS:BUILTIN_FLSH2" // dev_flash2
#define DEV_FLASH3 "CELL_FS_IOS:BUILTIN_FLSH3" // dev_flash3
#define DEV_BDVD "CELL_FS_IOS:BDVD_DRIVE" // dev_bdvd
#define DEV_USB0 "CELL_FS_IOS:USB_MASS_STORAGE000" // dev_usb000
#define DEV_USB1 "CELL_FS_IOS:USB_MASS_STORAGE001" // dev_usb001
#define DEV_USB2 "CELL_FS_IOS:USB_MASS_STORAGE002" // dev_usb002
#define DEV_USB3 "CELL_FS_IOS:USB_MASS_STORAGE003" // dev_usb003
#define DEV_USB4 "CELL_FS_IOS:USB_MASS_STORAGE004" // dev_usb004
#define DEV_USB5 "CELL_FS_IOS:USB_MASS_STORAGE005" // dev_usb005
#define DEV_USB6 "CELL_FS_IOS:USB_MASS_STORAGE006" // dev_usb006
#define DEV_USB7 "CELL_FS_IOS:USB_MASS_STORAGE007" // dev_usb007
#define DEV_HDD0 "CELL_FS_UTILITY:HDD0" // dev_hdd0
#define DEV_HDD1 "CELL_FS_UTILITY:HDD1" // dev_hdd1
#define DEV_DUMMY "CELL_FS_DUMMY" // app_home?
#define DEV_HOSTFS "CELL_FS_HOSTFS" // host_root and app_home
#define DEV_ADMINFS "CELL_FS_ADMINFS" // app_home?

// devices for older (non-slim) models
#define DEV_HDD_P0 "CELL_FS_IOS:PATA0_HDD_DRIVE" // maybe dev_hdd0
#define DEV_HDD_P1 "CELL_FS_IOS:PATA1_HDD_DRIVE" // maybe dev_hdd1
#define DEV_BDVD_P0 "CELL_FS_IOS:PATA0_BDVD_DRIVE" // dev_bdvd
#define DEV_BDVD_P1 "CELL_FS_IOS:PATA1_BDVD_DRIVE" // dev_bdvd
#define DEV_CF "CELL_FS_IOS:COMPACT_FLASH" // dev_cf
#define DEV_MS "CELL_FS_IOS:MEMORY_STICK" // dev_ms
#define DEV_SD "CELL_FS_IOS:SD_CARD" // dev_sd

// unknown devices
#define DEV_FLASH4 "CELL_FS_IOS:BUILTIN_FLSH4" // dev_flash4, unknown
#define DEV_HDD2 "CELL_FS_UTILITY:HDD2" // dev_hdd2, unknown
#define DEV_PSEUDO "CELL_FS_PSEUDO" // unknown

// filesystem types
#define FS_DUMMYFS "CELL_FS_DUMMYFS" // for CELL_FS_DUMMY
#define FS_ADMINFS "CELL_FS_ADMINFS" // for CELL_FS_HOSTFS
#define FS_FAT32 "CELL_FS_FAT" // for CELL_FS_IOS:BUILTIN_FLSH*, CELL_FS_IOS:USB_MASS_STORAGE***, and maybe more
#define FS_SIMPLEFS "CELL_FS_SIMPLEFS" // internally used for checking if drive is formattable
#define FS_UFS "CELL_FS_UFS" // for CELL_FS_UTILITY:HDD*
#define FS_UDF "CELL_FS_UDF" // for CELL_FS_IOS:BDVD_DRIVE
#define FS_ISO9660 "CELL_FS_ISO9660" // maybe dev_bdvd
#define FS_EFAT "CELL_FS_EFAT" // unknown
#define FS_PFAT "CELL_FS_PFAT" // unknown


LV2_SYSCALL lv2FsMyMount(const char* fsdev, const char* fs, const char* devpath)
{
  return Lv2Syscall3(SC_FS_MYMOUNT, (u64)fsdev, (u64)fs, (u64)devpath);
}

LV2_SYSCALL lv2FsMount(const char* fsdev, const char* fs, const char* devpath, s32 writeprot)
{
    return Lv2Syscall8(SC_FS_MOUNT, (u64)fsdev, (u64)fs, (u64)devpath, (s32)0, writeprot, (s32)0, (u64)NULL, (u32)0);
}

LV2_SYSCALL lv2FsUnMount(const char* devpath)
{
    return Lv2Syscall1(SC_FS_UMOUNT, (u64)devpath);
}

/*
 EXAMPLES
 
lv2FsMyMount("CELL_FS_IOS:USB_MASS_STORAGE003", "CELL_FS_UDF", TARGET_PATH);

lv2FsMyMount("CELL_FS_LOOPBACK:/dev_hdd0/test.iso", "CELL_FS_UDF", TARGET_PATH);

sprintf(buf, "CELL_FS_LOOPBACK:%s", srcpath);
lv2FsMyMount(buf, "CELL_FS_UDF", TARGET_PATH);

-----------------------------------------------------------

strings stuff.bin | grep CELL_
CELL_FS_UTILITY:HDD1
CELL_FS_FAT
CELL_FS_SIMPLEFS
CELL_FS_IOS:
CELL_FS_UTILITY:
CELL_FS_IOS:BUILTIN_FLASH
CELL_FS_IOS:BUILTIN_FLSH1
CELL_FS_IOS:BUILTIN_FLSH2
CELL_FS_IOS:BUILTIN_FLSH3
CELL_FS_IOS:BUILTIN_FLSH4
CELL_FS_IOS:ATA_HDD
CELL_FS_IOS:PATA1_HDD_DRIVE
CELL_FS_UTILITY:HDD0
CELL_FS_UTILITY:HDD1
CELL_FS_UTILITY:HDD2
CELL_FS_IOS:ATA_HDD
CELL_FS_EFAT
CELL_FS_PFAT
CELL_FS_LOOP:
CELL_FS_SIMPLE
CELL_FS_HOSTFS
CELL_FS_DUMMY:
CELL_FS_HOSTFS:
CELL_FS_IOS:BDVD_DRIVE
CELL_FS_IOS:PATA0_HDD_DRIVE
CELL_FS_IOS:PATA0_BDVD_DRIVE
CELL_FS_IOS:PATA1_HDD_DRIVE
CELL_FS_IOS:PATA1_BDVD_DRIVE
CELL_FS_IOS:BUILTIN_FLASH
CELL_FS_IOS:COMPACT_FLASH
CELL_FS_IOS:MEMORY_STICK
CELL_FS_IOS:SD_CARD
CELL_FS_IOS:USB_MASS_STORAGE000
CELL_FS_IOS:USB_MASS_STORAGE001
CELL_FS_IOS:USB_MASS_STORAGE002
CELL_FS_IOS:USB_MASS_STORAGE003
CELL_FS_IOS:USB_MASS_STORAGE004
CELL_FS_IOS:USB_MASS_STORAGE005
CELL_FS_IOS:USB_MASS_STORAGE
CELL_FS_IOS:BUILTIN_FLSH1
CELL_FS_IOS:BUILTIN_FLSH2
CELL_FS_IOS:BUILTIN_FLSH3
CELL_FS_IOS:BUILTIN_FLSH4
CELL_FS_UTILITY:HDD0
CELL_FS_UTILITY:HDD1
CELL_FS_UTILITY:HDD2
CELL_FS_UTILITY:HDD
CELL_FS_PSEUDO:
CELL_FS_ADMINFS:
CELL_FS_IOS:PATA0_HDD_DRIVE
CELL_FS_IOS:PATA1_HDD_DRIVE
CELL_FS_IOS:PATA0_BDVD_DRIVE
CELL_FS_IOS:PATA1_BDVD_DRIVE
CELL_FS_IOS:BUILTIN_FLASH
CELL_FS_IOS:USB_MASS_STORAGE
CELL_FS_ADMINFS:
CELL_FS_DUMMY:
CELL_FS_DUMMY:/
CELL_FS_ADMINFS
CELL_FS_UDF
CELL_FS_ISO9660
CELL_FS_DUMMYFS
CELL_FS_UFS
CELL_FS_ADMINFS:
CELL_FS_ADMINFS
CELL_FS_DUMMY:
CELL_FS_DUMMYFS
CELL_FS_DUMMY:/
CELL_FS_DUMMYFS
CELL_FS_IOS:BUILTIN_FLSH1
CELL_FS_FAT
CELL_FS_IOS:BUILTIN_FLSH1
CELL_FS_FAT
CELL_FS_IOS:BUILTIN_FLSH1
CELL_FS_FAT
CELL_FS_IOS:BUILTIN_FLSH2
CELL_FS_SIMPLEFS
CELL_FS_IOS:BUILTIN_FLSH2
CELL_FS_SIMPLEFS
CELL_FS_IOS:BUILTIN_FLSH2
CELL_FS_FAT
        CELL_FS_IOS:BUILTIN_FLSH3
CELL_FS_FAT
CELL_FS_UTILITY:HDD0
CELL_FS_SIMPLEFS
CELL_FS_UTILITY:HDD0
CELL_FS_UFS
CELL_FS_UTILITY:HDD1
CELL_FS_FAT
CELL_FS_IOS:USB_MASS_STORAGE002
CELL_FS_FAT
CELL_FS_UTILITY:HDD1
CELL_FS_FAT
CELL_FS_ADMINFS
CELL_FS_UDF
CELL_FS_ISO9660
CELL_FS_SIMPLEFS
CELL_FS_FAT
CELL_FS_EFAT
CELL_FS_DUMMYFS
CELL_FS_UFS
CELL_FS_IOS:USB_MASS_STORAGE006
CELL_FS_IOS:USB_MASS_STORAGE007
CELL_FS_IOS:USB_MASS_STORAGE008
CELL_FS_IOS:USB_MASS_STORAGE009
CELL_FS_IOS:USB_MASS_STORAGE010
CELL_FS_IOS:USB_MASS_STORAGE011
CELL_FS_IOS:USB_MASS_STORAGE012
CELL_FS_IOS:USB_MASS_STORAGE013
CELL_FS_IOS:USB_MASS_STORAGE014
CELL_FS_IOS:USB_MASS_STORAGE015
CELL_FS_IOS:USB_MASS_STORAGE016
CELL_FS_IOS:USB_MASS_STORAGE017
CELL_FS_IOS:USB_MASS_STORAGE018
CELL_FS_IOS:USB_MASS_STORAGE019
CELL_FS_IOS:USB_MASS_STORAGE020
CELL_FS_IOS:USB_MASS_STORAGE021
CELL_FS_IOS:USB_MASS_STORAGE022
CELL_FS_IOS:USB_MASS_STORAGE023
CELL_FS_IOS:USB_MASS_STORAGE024
CELL_FS_IOS:USB_MASS_STORAGE025
CELL_FS_IOS:USB_MASS_STORAGE026
CELL_FS_IOS:USB_MASS_STORAGE027
CELL_FS_IOS:USB_MASS_STORAGE028
CELL_FS_IOS:USB_MASS_STORAGE029
CELL_FS_IOS:USB_MASS_STORAGE030
CELL_FS_IOS:USB_MASS_STORAGE031
CELL_FS_IOS:USB_MASS_STORAGE032
CELL_FS_IOS:USB_MASS_STORAGE033
CELL_FS_IOS:USB_MASS_STORAGE034
CELL_FS_IOS:USB_MASS_STORAGE035
CELL_FS_IOS:USB_MASS_STORAGE036
CELL_FS_IOS:USB_MASS_STORAGE037
CELL_FS_IOS:USB_MASS_STORAGE038
CELL_FS_IOS:USB_MASS_STORAGE039
CELL_FS_IOS:USB_MASS_STORAGE040
CELL_FS_IOS:USB_MASS_STORAGE041
CELL_FS_IOS:USB_MASS_STORAGE042
CELL_FS_IOS:USB_MASS_STORAGE043
CELL_FS_IOS:USB_MASS_STORAGE044
CELL_FS_IOS:USB_MASS_STORAGE045
CELL_FS_IOS:USB_MASS_STORAGE046
CELL_FS_IOS:USB_MASS_STORAGE047
CELL_FS_IOS:USB_MASS_STORAGE048
CELL_FS_IOS:USB_MASS_STORAGE049
CELL_FS_IOS:USB_MASS_STORAGE050
CELL_FS_IOS:USB_MASS_STORAGE051
CELL_FS_IOS:USB_MASS_STORAGE052
CELL_FS_IOS:USB_MASS_STORAGE053
CELL_FS_IOS:USB_MASS_STORAGE054
CELL_FS_IOS:USB_MASS_STORAGE055
CELL_FS_IOS:USB_MASS_STORAGE056
CELL_FS_IOS:USB_MASS_STORAGE057
CELL_FS_IOS:USB_MASS_STORAGE058
CELL_FS_IOS:USB_MASS_STORAGE059
CELL_FS_IOS:USB_MASS_STORAGE060
CELL_FS_IOS:USB_MASS_STORAGE061
CELL_FS_IOS:USB_MASS_STORAGE062
CELL_FS_IOS:USB_MASS_STORAGE063
CELL_FS_IOS:USB_MASS_STORAGE064
CELL_FS_IOS:USB_MASS_STORAGE065
CELL_FS_IOS:USB_MASS_STORAGE066
CELL_FS_IOS:USB_MASS_STORAGE067
CELL_FS_IOS:USB_MASS_STORAGE068
CELL_FS_IOS:USB_MASS_STORAGE069
CELL_FS_IOS:USB_MASS_STORAGE070
CELL_FS_IOS:USB_MASS_STORAGE071
CELL_FS_IOS:USB_MASS_STORAGE072
CELL_FS_IOS:USB_MASS_STORAGE073
CELL_FS_IOS:USB_MASS_STORAGE074
CELL_FS_IOS:USB_MASS_STORAGE075
CELL_FS_IOS:USB_MASS_STORAGE076
CELL_FS_IOS:USB_MASS_STORAGE077
CELL_FS_IOS:USB_MASS_STORAGE078
CELL_FS_IOS:USB_MASS_STORAGE079
CELL_FS_IOS:USB_MASS_STORAGE080
CELL_FS_IOS:USB_MASS_STORAGE081
CELL_FS_IOS:USB_MASS_STORAGE082
CELL_FS_IOS:USB_MASS_STORAGE083
CELL_FS_IOS:USB_MASS_STORAGE084
CELL_FS_IOS:USB_MASS_STORAGE085
CELL_FS_IOS:USB_MASS_STORAGE086
CELL_FS_IOS:USB_MASS_STORAGE087
CELL_FS_IOS:USB_MASS_STORAGE088
CELL_FS_IOS:USB_MASS_STORAGE089
CELL_FS_IOS:USB_MASS_STORAGE090
CELL_FS_IOS:USB_MASS_STORAGE091
CELL_FS_IOS:USB_MASS_STORAGE092
CELL_FS_IOS:USB_MASS_STORAGE093
CELL_FS_IOS:USB_MASS_STORAGE094
CELL_FS_IOS:USB_MASS_STORAGE095
CELL_FS_IOS:USB_MASS_STORAGE096
CELL_FS_IOS:USB_MASS_STORAGE097
CELL_FS_IOS:USB_MASS_STORAGE098
CELL_FS_IOS:USB_MASS_STORAGE099
CELL_FS_IOS:USB_MASS_STORAGE100
CELL_FS_IOS:USB_MASS_STORAGE101
CELL_FS_IOS:USB_MASS_STORAGE102
CELL_FS_IOS:USB_MASS_STORAGE103
CELL_FS_IOS:USB_MASS_STORAGE104
CELL_FS_IOS:USB_MASS_STORAGE105
CELL_FS_IOS:USB_MASS_STORAGE106
CELL_FS_IOS:USB_MASS_STORAGE107
CELL_FS_IOS:USB_MASS_STORAGE108
CELL_FS_IOS:USB_MASS_STORAGE109
CELL_FS_IOS:USB_MASS_STORAGE110
CELL_FS_IOS:USB_MASS_STORAGE111
CELL_FS_IOS:USB_MASS_STORAGE112
CELL_FS_IOS:USB_MASS_STORAGE113
CELL_FS_IOS:USB_MASS_STORAGE114
CELL_FS_IOS:USB_MASS_STORAGE115
CELL_FS_IOS:USB_MASS_STORAGE116
CELL_FS_IOS:USB_MASS_STORAGE117
CELL_FS_IOS:USB_MASS_STORAGE118
CELL_FS_IOS:USB_MASS_STORAGE119
CELL_FS_IOS:USB_MASS_STORAGE120
CELL_FS_IOS:USB_MASS_STORAGE121
CELL_FS_IOS:USB_MASS_STORAGE122
CELL_FS_IOS:USB_MASS_STORAGE123
CELL_FS_IOS:USB_MASS_STORAGE124
CELL_FS_IOS:USB_MASS_STORAGE125
CELL_FS_IOS:USB_MASS_STORAGE126
CELL_FS_IOS:USB_MASS_STORAGE127
CELL_FS_DUMMY
CELL_FS_UDF
CELL_FS_HOSTFS
CELL_FS_IOS:COMPACT_FLASH
CELL_FS_IOS:MEMORY_STICK
CELL_FS_IOS:SD_CARD
CELL_FS_IOS:USB_MASS_STORAGE000
CELL_FS_IOS:USB_MASS_STORAGE001
CELL_FS_IOS:USB_MASS_STORAGE002
CELL_FS_IOS:USB_MASS_STORAGE003
CELL_FS_IOS:USB_MASS_STORAGE
CELL_FS_PSEUDO
CELL_FS_ADMINFS
CELL_FS_DUMMYFS
CELL_FS_FAT
CELL_FS_SIMPLEFS
CELL_FS_UFS
CELL_FS_ISO9660
CELL_FS_EFAT
CELL_FS_PFAT
CELL_FS_IOS:USB_MASS_STORAGE002

http://www.ps3news.com/PS3-Hacks/ps3mrenigma-on-ps3-mount-points-filesystems-and-alejandro/

*/

#endif /* MOUNT_H */
